
site_name: Granblue Fantasy - Relink Modding
site_description: Granblue Fantasy - Relink Modding Docs
site_url: https://nenkai.github.io/relink-modding/
repo_url: https://github.com/Nenkai/relink-modding
repo_name: nenkai/relink-modding

copyright: Copyright &copy; 2024 Nenkai - Not affiliated with Cygames.

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.code.annotate
    - header.autohide
  language: en
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
    primary: light blue
    accent: light blue 

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: light blue
    accent: light blue 

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    primary: light blue
    accent: light blue


nav:
  - Main Page: index.md
  - Modding Tutorials: 
    - Installing Mods: modding/installing_mods.md
    - Creating Mods: modding/creating_mods.md

  - Modder Tutorials:
    - Extracting Files: extraction/file_extraction.md
    - Extracting Textures: extraction/texture_extraction.md
    - Creating Textures: extraction/texture_creation.md

  - Modder Resources/Info:
    - Asset Paths: resources/asset_paths.md
    - File Extensions: resources/file_extensions.md
    - Entity Prefixes: resources/entity_prefixes.md

    - IDs:
      - Model IDs: resources/model_ids.md
      - Item IDs: resources/item_ids.md
      - Sigil/Gem IDs: resources/sigil_gem_ids.md
      - Trait/Skill IDs: resources/trait_skill_ids.md
      - Quest IDs: resources/quest_ids.md

    - Rates/Tables:
      - Quest Drop Rates: resources/quest_drop_rates.md
      - Curio Loot Rates: resources/curio_loot_rates.md
      - Weapon Materials: resources/weapon_materials.md

    - Formats:
        .minfo - Model Info: resources/formats/minfo.md
        .mmat - Material Info: resources/formats/mmat.md
        .objread - Obj Read: resources/formats/objread.md
    - Reverse-Engineering:
        Hashes: resources/re/hashes.md
        Obj IDs: resources/re/obj_id.md
        User Attributes: resources/re/user_attributes.md
      
  - Blender:
    - Model Importing: models/importing.md 
    - Model Exporting: models/exporting.md

  - Tables:
    - Table Database: tables/table_database.md

  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: nenkai/relink-modding
      branch: main
  - social
  - search:
      lang: en
  - glightbox
  - table-reader
      
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/gbsG4CDsru

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Nenkaai

    - icon: fontawesome/brands/github 
      link: https://github.com/Nenkai

    - icon: simple/kofi
      link: https://ko-fi.com/nenkai

extra_css:
  - stylesheets/extra.css